version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/python:3.6
        environment:
          PGHOST: 127.0.0.1
          DATABASE_URL: "postgis://postgres:postgres@localhost:5432/circle_test"
      - image: circleci/postgres:9.5-alpine-postgis
        environment:
          POSTGRES_USER: postgres
          PGUSER: postgres
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: postgres
    steps:
      - checkout
      - run:
          name: create main virtualenv, install requirements
          command: |
            python3 -m venv env1
            . env1/bin/activate
            pip install -r requirements/dev.txt
      - run:
          name: run tests
          command: |
            . env1/bin/activate
            coverage run manage.py test
      - run:
          name: report coverage
          command: |
            . env1/bin/activate
            coverage report
  package:
    working_directory: ~/code
    docker:
      - image: circleci/python:3.6
        environment:
          PGHOST: 127.0.0.1
          DATABASE_URL: "postgis://postgres:postgres@localhost:5432/circle_test"
      - image: circleci/postgres:9.5-alpine-postgis
        environment:
          POSTGRES_USER: postgres
          PGUSER: postgres
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: postgres
    steps:
      - checkout
      - run:
          name: create main virtualenv, install requirements
          command: |
            python3 -m venv env1
            . env1/bin/activate
            pip install -r requirements/dev.txt
      - run:
          name: verify git tag vs version
          command: |
            . env1/bin/activate
            python3 setup.py verify
      - run:
          name: init .pypirc
          command: |
            echo -e "[distutils]" >> ~/.pypirc
            echo -e "index-servers =" >> ~/.pypirc
            echo -e "    pypi" >> ~/.pypirc
            echo -e "" >> ~/.pypirc
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username: $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password: $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: create and upload package
          command: |
            . env1/bin/activate
            python setup.py sdist upload

workflows:
  version: 2
  build_and_package:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - package:
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
