# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-05 18:10
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('approve', models.PositiveIntegerField()),
                ('disapprove', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ChildrensBook',
            fields=[
                ('book_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    serialize=False,
                    to='sample.Book'
                )),
                ('max_age', models.PositiveIntegerField()),
            ],
            bases=('sample.book',),
        ),
        migrations.AddField(
            model_name='stats',
            name='book',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to='sample.Book'
            ),
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='books',
                to='sample.Author'
            ),
        ),
        migrations.AddField(
            model_name='book',
            name='previous',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='next',
                to='sample.Book'
            ),
        ),
    ]
