# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 17:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
        ('example', '0001_initial'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Realm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this realm belongs to. A realm will get all permissions granted to each of their groups.', related_name='realm_set', related_query_name='realm', to='auth.Group', verbose_name='groups')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='example.Organization')),
                ('realm_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this realm.', related_name='realm_set', related_query_name='realm', to='auth.Permission', verbose_name='realm permissions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant.Workspace')),
            ],
        ),
    ]
